# Data Pre-processing 

In [10]:
## Importing libraries 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [11]:
## the below code imports the data from the csv file into a pandas data frame
data_pre_process = pd.read_csv("C:\\Users\\supra\\Desktop\\108_days_of_ML\\Day_1_Data_preprocessing\\Data.csv")
## To check the imported data 
data_pre_process.head(10)


Country   Age   Salary Purchased
0       India  44.0  72000.0        No
1    SriLanka  27.0  48000.0       Yes
2  Bangladesh  30.0  54000.0        No
3    SriLanka  38.0  61000.0        No
4  Bangladesh  40.0      NaN       Yes
5       India  35.0  58000.0       Yes
6    SriLanka   NaN  52000.0        No
7       India  48.0  79000.0       Yes
8  Bangladesh  50.0  83000.0        No
9       India  37.0  67000.0       Yes

In [14]:
## Extracting the dependent and indenpendent variables 
## Independent Variable - These are the factors that are used in the model to predict the Target Variable 
## eg. Country, Age and Salary could be used to predict Puchasability of a Car/House etc., Hence, Country, Age, Salary can be considered as independent variable
X = data_pre_process.iloc[:, :-1].values
## Dependent Variable or Target Variable : It is the variable of interest which is studided or for which the model is built.
Y = data_pre_process.iloc[:, -1].values

In [15]:
## Checking Dependent variables
print(X)

[['India' 44.0 72000.0]
 ['SriLanka' 27.0 48000.0]
 ['Bangladesh' 30.0 54000.0]
 ['SriLanka' 38.0 61000.0]
 ['Bangladesh' 40.0 nan]
 ['India' 35.0 58000.0]
 ['SriLanka' nan 52000.0]
 ['India' 48.0 79000.0]
 ['Bangladesh' 50.0 83000.0]
 ['India' 37.0 67000.0]]


In [16]:
##Checking Independent variable 
print(Y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [ ]:
## There are two prominent ways to handle a missing data:
##  1.Deleting the particular row - This method is not optimal as this could lead to loss of Data. 
##  2.calculating the mean: Calculating the mean of that column or row which contains any missing value and will put it on the place of missing value.

In [ ]:
# To handle missing values, we will use Scikit-learn library in our code, which contains various libraries for building machine learning models. 
# Here we will use SimpleImputer class of sklearn.impute library.

In [17]:
#handling missing data (Replacing missing data with the mean value)  
from sklearn.impute import SimpleImputer 
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [18]:
#checking the replaced data 
print(X)

[['India' 44.0 72000.0]
 ['SriLanka' 27.0 48000.0]
 ['Bangladesh' 30.0 54000.0]
 ['SriLanka' 38.0 61000.0]
 ['Bangladesh' 40.0 63777.77777777778]
 ['India' 35.0 58000.0]
 ['SriLanka' 38.77777777777778 52000.0]
 ['India' 48.0 79000.0]
 ['Bangladesh' 50.0 83000.0]
 ['India' 37.0 67000.0]]


In [ ]:
# Since machine learning model works on mathematics and numbers, but if the dataset would have a categorical variable, then it may create trouble while building the model. 
# So it is necessary to encode these categorical variables into numbers.

In [23]:
## Encoding Independent variables
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(),[0])],remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [24]:
##checking ohe
print(X)

[[0.0 1.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 48.0 79000.0]
 [1.0 0.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 37.0 67000.0]]


In [25]:
## Encoding Dependent variables
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y = le.fit_transform(Y)

In [26]:
##checking ohe
print(Y)

[0 1 0 0 1 1 0 1 0 1]


In [ ]:
# Training Set: A subset of dataset to train the machine learning model, and we already know the output.
# Test set: A subset of dataset to test the machine learning model, and by using the test set, model predicts the output.

In [ ]:
# In the below code, the first line is used for splitting arrays of the dataset into random train and test subsets.
# In the second line, we have used four variables for our output that are
# x_train: features for the training data
# x_test: features for testing data
# y_train: Dependent variables for training data
# y_test: Independent variable for testing data

# In train_test_split() function, we have passed four parameters in which first two are for arrays of data, 
# and test_size is for specifying the size of the test set. 
# The test_size maybe .5, .3, or .2, which tells the dividing ratio of training and testing sets.

# The last parameter random_state is used to set a seed for a random generator so that you always get the same result, and the most used value for this is 42.

In [27]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X,Y, test_size = 0.2, random_state = 1)

In [28]:
print(x_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 48.0 79000.0]
 [1.0 0.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 35.0 58000.0]]


In [29]:
print(x_test)

[[1.0 0.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 37.0 67000.0]]


In [30]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [31]:
print(y_test)

[0 1]


In [ ]:
# Feature scaling is the final step of data preprocessing in machine learning. 
# It is a technique to standardize the independent variables of the dataset in a specific range. 
# In feature scaling, we put the variables in the same range and in the same scale so that no any variable dominate the other variable.

In [33]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [34]:
print(x_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [1.0 0.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [0.0 1.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [0.0 1.0 0.0 1.1475343068237058 1.232653363453549]
 [1.0 0.0 0.0 1.4379472069688968 1.5749910381638885]
 [0.0 1.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [35]:
print(x_test)

[[1.0 0.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [0.0 1.0 0.0 -0.44973664397484414 0.2056403393225306]]
